'use client'
import { ChakraProvider, Grid, GridItem } from '@chakra-ui/react'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Sidebar } from './components/Sidebar'
import { Header } from './components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<ChakraProvider>
					<Grid
						p={0}
						className='max-h-screen w-screen'
						templateColumns={'auto 1fr'}
						templateRows={'auto 1fr'}
					>
						<GridItem colStart={2}>
							<Header />
						</GridItem>
						<GridItem rowStart={1} rowSpan={2} h={'full'}>
							<Sidebar />
						</GridItem>
						<GridItem>{children}</GridItem>
					</Grid>
				</ChakraProvider>
			</body>
		</html>
	)
}
